### ISSUE TITLE
writeBulk not working

### ISSUE THREAD

**Issue by TotallyInformation** [beebotte/bbt_node#9]
I am trying a simple test and I can't get it to work.
Firstly there is an error in the example at http://beebotte.com/tutorials/activity_reporter, the example code for writeBulk is incorrect.
Secondly, though I only have 5 resources defined in my channel. I've even tried setting them to type "any", I always get an error.

The error is: { error:
   { message: '[{"message":"data is not allowed","path":"data","type":"object.allowUnknown"}]',
     code: 11 } }

The data is: { Uno1Temp: 17,
  Uno1Humid: 39,
  TH1Temp: 15.6,
  TH1Humid: 49,
  Uno1Light: 144 }

**Comment by bachwehbi** [comment]
Thanks for reporting this!

Indeed, the code for writeBulk in https://beebotte.com/tutorials/activity_reporter tutorial was not correct (fixed). 
The JSON message format should be:
```javascript
{
  "channel": "channel_name",
  "records": [
    {"resource": "resource_1_name", "data": 123},
    {"resource": "resource_2_name", "data": 456},
  ]
}
```

The error you are getting indicates that the format of the data you are sending is not correct. Please check the documentation http://beebotte.com/docs/write of the write API for more details. 

This is an example using writeBulk:

```javascript
var bbt = require('beebotte');
var bclient = new bbt.Connector({
    keyId: 'YOUR_ACCESS_KEY',
    secretKey: 'YOUR_SECRET_KEY'
});

bclient.writeBulk({channel: 'test', records: [
    { resource: 'Uno1Temp', data: 17},
    { resource: 'Uno1Humid', data : 39},
    { resource: 'TH1Temp', data: 15.6},
    { resource: 'TH1Humid', data: 49},
    { resource: 'Uno1Light', data: 144}
  ]}, function(err, res) {
    if(err) return console.log(err);
    console.log(res);
});
```
